---
# Deploy Prometheus
- name: Run Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    ports:
      - "9090:9090"

# Create SNMP Exporter configuration
- name: Ensure SNMP Exporter config directory exists
  ansible.builtin.file:
    path: /etc/snmp_exporter/
    state: directory
    mode: '0755'

# Copy SNMP YAML to remote host
- name: Copy dashboard.json to remote host
  ansible.builtin.copy:
    src: "/Users/davidking/Documents/developer/IaC_VM/snmp.yml"
    dest: "/etc/snmp_exporter/snmp.yml"
    mode: '0644'

# Run the SNMP Exporter container
- name: Run SNMP Exporter container
  community.docker.docker_container:
    name: snmp_exporter
    image: prom/snmp-exporter:latest
    state: started
    restart: true
    ports:
      - "9116:9116"
    volumes:
      - "/etc/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml"

# Create Prometheus configuration to scrape SNMP Exporter
- name: Ensure Prometheus config directory exists
  ansible.builtin.file:
    path: /etc/prometheus/
    state: directory
    mode: '0644'

#  - '{{ your_second_arista_switch_ip }}'  Additional switch to be monitored
- name: Write Prometheus configuration for SNMP Exporter
  ansible.builtin.copy:
    dest: "/etc/prometheus/prometheus.yml"
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'snmp'
          static_configs:
            - targets:
              - '{{ your_arista_switch_ip }}'
          metrics_path: /snmp
          params:
            module: [if_mib]
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: {{ ansible_host }}:9116  # SNMP Exporter address
    mode: '0644'

- name: Restart_Prometheus
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    ports:
      - "9090:9090"
    volumes:
      - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

# Connect Prometheus to Grafana
- name: Wait for Grafana to start up before configuring
  ansible.builtin.wait_for:
    port: 3000
    delay: 10

- name: Add Prometheus data source to Grafana
  community.grafana.grafana_datasource:
    url: http://localhost:3000
    url_username: "{{ grafana_admin }}"
    url_password: "{{ grafana_password }}"
    ds_type: prometheus
    name: Prometheus
    ds_url: http://{{ ansible_host }}:9090
    access: proxy
    state: "{{ installed_state }}"

# Copy Grafana dashboard to remote host
- name: Copy dashboard.json to remote host
  ansible.builtin.copy:
    src: "/Users/davidking/Documents/developer/IaC_VM/dashboard.json"
    dest: "/tmp/dashboard.json"
    mode: '0644'

# Create Grafana dashboard
- name: Create Grafana Dashboard
  community.grafana.grafana_dashboard:
    url: http://localhost:3000
    url_username: "{{ grafana_admin }}"
    url_password: "{{ grafana_password }}"
    state: "{{ installed_state }}"
    overwrite: true
    commit_message: "Updated by Ansible"
    path: "/tmp/dashboard.json"
