---
# CONFIG Prometheus

#  - '{{ your_second_arista_switch_ip }}'  Additional switch to be monitored
- name: Write Prometheus configuration for SNMP Exporter
  ansible.builtin.copy:
    dest: "/etc/prometheus/prometheus.yml"
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'snmp'
          static_configs:
            - targets:
              - '{{ your_arista_switch_ip }}'
          metrics_path: /snmp
          params:
            module: [if_mib]
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: {{ ansible_host }}:9116  # SNMP Exporter address
    mode: '0644'

- name: Restart the Prometheus Container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart: true
    ports:
      - "9090:9090"
    volumes:
      - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  # notify:
  #   - Restart_Prometheus
