all:
  children:
    network:
      children:
        switches:
          children:
            arista:
              hosts:
                AristaSwitch:
                  ansible_host: 192.168.5.111
                  ansible_network_os: arista.eos.eos
                  ansible_connection: ansible.netcommon.network_cli
                  ansible_become: true
                  ansible_become_method: enable
                cisco:
                  hosts:
                    ciscoswitch:
                      ansible_host: 192.168.4.204
    source_of_truth:
      hosts:
        netbox:
          ansible_host: 192.168.4.85
