---
# Connect Prometheus to Grafana
- name: Wait for Grafana to start up before configuring
  ansible.builtin.wait_for:
    port: 3000
    delay: 10

- name: Add Prometheus data source to Grafana
  community.grafana.grafana_datasource:
    url: http://localhost:3000
    url_username: "{{ grafana_admin }}"
    url_password: "{{ grafana_password }}"
    ds_type: prometheus
    name: Prometheus
    ds_url: http://{{ ansible_host }}:9090
    access: proxy
    state: "{{ installed_state }}"
