---
# Copy Grafana dashboard to remote host
- name: Copy dashboard.json to remote host
  ansible.builtin.copy:
    src: "/Users/davidking/Documents/developer/IaC_VM/dashboard.json"
    dest: "/tmp/dashboard.json"
    mode: '0644'

# Create Grafana dashboard
- name: Create Grafana Dashboard
  community.grafana.grafana_dashboard:
    url: http://localhost:3000
    url_username: "{{ grafana_admin }}"
    url_password: "{{ grafana_password }}"
    state: "{{ installed_state }}"
    overwrite: true
    commit_message: "Updated by Ansible"
    path: "/tmp/dashboard.json"
